import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { useSelector } from 'react-redux';

export default function Home() {
  const router = useRouter()
  const theme = useSelector(state => state.theme.value)

  useEffect(()=>{
    router.push("/countries")
  },[])
  return (
    <div className={`${theme == "dark" ? "dark" : "light"}`}>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      home
    </div>
  )
}
